// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYKCX1-Gt_AOzO03ytNvwhD2mbZ0uq9eM',
    appId: '1:52198417453:web:fbf95127137deed52604a4',
    messagingSenderId: '52198417453',
    projectId: 'proyectomovil-54f19',
    authDomain: 'proyectomovil-54f19.firebaseapp.com',
    storageBucket: 'proyectomovil-54f19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzi7UtG9TKXvMlHeYnQPNoZHZAOAx5mxE',
    appId: '1:52198417453:android:15e45e443a63177b2604a4',
    messagingSenderId: '52198417453',
    projectId: 'proyectomovil-54f19',
    storageBucket: 'proyectomovil-54f19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-me5jfYkuAmy_WvpJTa_Ddw6xydxtKq0',
    appId: '1:52198417453:ios:179ca3d2f058eb742604a4',
    messagingSenderId: '52198417453',
    projectId: 'proyectomovil-54f19',
    storageBucket: 'proyectomovil-54f19.firebasestorage.app',
    iosBundleId: 'com.example.mediscanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-me5jfYkuAmy_WvpJTa_Ddw6xydxtKq0',
    appId: '1:52198417453:ios:179ca3d2f058eb742604a4',
    messagingSenderId: '52198417453',
    projectId: 'proyectomovil-54f19',
    storageBucket: 'proyectomovil-54f19.firebasestorage.app',
    iosBundleId: 'com.example.mediscanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYKCX1-Gt_AOzO03ytNvwhD2mbZ0uq9eM',
    appId: '1:52198417453:web:acebe94f2d3f05f72604a4',
    messagingSenderId: '52198417453',
    projectId: 'proyectomovil-54f19',
    authDomain: 'proyectomovil-54f19.firebaseapp.com',
    storageBucket: 'proyectomovil-54f19.firebasestorage.app',
  );
}
